<?php
/**
 * JulioReis_CorreiosFollowup
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  JulioReis
 * @package   JulioReis_CorreiosFollowup
 *
 * @copyright Copyright (c) 2018 Julio Reis (www.rapidets.com.br)
 *
 * @author    Julio Reis <julioreis.si@gmail.com>
 */

namespace JulioReis\CorreiosFollowup\Observer;

use Magento\Framework\Event\Observer;

class Tracker implements \Magento\Framework\Event\ObserverInterface
{
    /** @var \Magento\Sales\Model\Order\Email\Sender\ShipmentCommentSenderFactory */
    protected $shipmentCommentSenderFactory;

    /**
     * Tracker constructor.
     * @param \Magento\Sales\Model\Order\Email\Sender\ShipmentCommentSenderFactory $shipmentCommentSenderFactory
     */
    public function __construct(
        \Magento\Sales\Model\Order\Email\Sender\ShipmentCommentSenderFactory $shipmentCommentSenderFactory
    )
    {
        $this->shipmentCommentSenderFactory = $shipmentCommentSenderFactory;
    }

    /**
     * @param Observer $observer
     */
    public function execute(Observer $observer)
    {
        $shipment = $observer->getShipment();
        $message = $observer->getMessage();
        $shipmentCommentSender = $this->shipmentCommentSenderFactory->create();
        $shipmentCommentSender->send($shipment, $message, $message);
    }
}