<?php
/**
 * JulioReis_CorreiosFollowup
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  JulioReis
 * @package   JulioReis_CorreiosFollowup
 *
 * @copyright Copyright (c) 2018 Julio Reis (www.rapidets.com.br)
 *
 * @author    Julio Reis <julioreis.si@gmail.com>
 */

namespace JulioReis\CorreiosFollowup\Model;

use Magento\Framework\Model\AbstractModel;

class Service extends AbstractModel
{
    public function getTrackingStatuses($codigoRastreio)
    {
        $url = 'http://www2.correios.com.br/sistemas/rastreamento/ctrl/ctrlRastreamento.cfm?';
        $post = ("acao=&objetos={$codigoRastreio}");
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
        curl_setopt($ch, CURLOPT_COOKIEFILE, '/tmp/cookie.txt');
        curl_setopt($ch, CURLOPT_COOKIEJAR, '/tmp/cookie.txt');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_REFERER, $url);
        $content = curl_exec($ch);
        curl_close($ch);

        $dom = new \DOMDocument;
        $dom->loadHTML($content);

        $listDates = $this->getElementsByClassName($dom, 'sroDtEvent');

        $trackingLines = [];
        foreach ($listDates as $event) {
            $trackingLines[][0] = $this->formatString($event->nodeValue);
        }

        $listStatuses = $this->getElementsByClassName($dom, 'sroLbEvent');

        $index = 0;
        foreach ($listStatuses as $event) {
            $trackingLines[$index][1] = $this->formatString($event->nodeValue);
            $index++;
        }
        return $trackingLines;
    }

    private function getElementsByClassName($dom, $className)
    {
        $finder = new \DomXPath($dom);
        return $finder->query("//*[contains(concat(' ', normalize-space(@class), ' '), ' $className ')]");
    }

    private function formatString($str)
    {
        return ltrim(rtrim(str_replace("\r", '', $str)));
    }
}