<?php
/**
 * JulioReis_CorreiosFollowup
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  JulioReis
 * @package   JulioReis_CorreiosFollowup
 *
 * @copyright Copyright (c) 2018 Julio Reis (www.rapidets.com.br)
 *
 * @author    Julio Reis <julioreis.si@gmail.com>
 */

namespace JulioReis\CorreiosFollowup\Model\Tracking;

use JulioReis\CorreiosFollowup\Model\ResourceModel\Tracking\Queue\CollectionFactory as QueueCollectionFactory;
use JulioReis\CorreiosFollowup\Model\ResourceModel\Tracking\QueueFactory as QueueResourceFactory;
use JulioReis\CorreiosFollowup\Model\Tracking\Queue as Queue;

class QueueRepository
{

    /** @var QueueFactory */
    protected $queueFactory;

    /** @var QueueCollectionFactory */
    protected $queueCollectionFactory;

    /** @var QueueResourceFactory */
    protected $queueResourceFactory;


    public function __construct(
        QueueFactory $queueFactory,
        QueueCollectionFactory $queueCollectionFactory,
        QueueResourceFactory $queueResourceFactory
    )
    {
        $this->queueFactory = $queueFactory;
        $this->queueCollectionFactory = $queueCollectionFactory;
        $this->queueResourceFactory = $queueResourceFactory;
    }

    public function loadByShipmentTrackId($shipmentTrackId)
    {
        $queue = $this->queueFactory->create();
        $this->getResource()->load($queue, $shipmentTrackId, 'shipment_track_id');
        return $queue;
    }

    /**
     * @param Queue $queue
     * @return Queue
     */
    public function save(Queue $queue)
    {
        if (!$queue->getId()) {
            $queue->setCreatedAt(date('Y-m-d H:i:s'));
        }
        $queue->setUpdatedAt(date('Y-m-d H:i:s'));
        $this->getResource()->save($queue);
        return $queue;
    }

    /**
     * @param Queue $queue
     * @return Queue
     */
    public function delete(Queue $queue)
    {
        $this->getResource()->delete($queue);
        return $queue;
    }

    /**
     * @return \JulioReis\CorreiosFollowup\Model\ResourceModel\Tracking\Queue\Collection
     */
    public function getCollection()
    {
        return $this->queueCollectionFactory->create();
    }

    public function getPendingTracks() {
        $collection = $this->getCollection();
        $collection->addFieldToFilter('correios_status',
            [
                'in' => [
                    \JulioReis\CorreiosFollowup\Model\Tracking\Queue::CORREIOS_STATUS_PROCESSING
                ]
            ]
        );
        return $collection;
    }

    /**
     * @return \JulioReis\CorreiosFollowup\Model\ResourceModel\Tracking\Queue
     */
    protected function getResource()
    {
        return $this->queueResourceFactory->create();
    }
}
